server:
  port: 8085
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.dayuan.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123

dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://182.61.34.250:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    timeout: 5000
